baseURL = ""
languageCode = "en-us"
title = "HeinrichHartmann.com"
# relativeurls = true
# uglyurls = true
pygmentsUseClasses = true
publishDir="../public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Only posts from mainSections appear in index
  mainSections = ["posts"]


#
# Output format to publish raw HTML posts
#
[outputFormats]
  [outputFormats.RawHTML]
    mediaType = "text/html"
    baseName = "index"
    isPlainText = false
    notAlternative = true
