# markdown: rdiscount
markdown: kramdown

highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      author: "Heinrich Hartmann"
      layout: "post"
