name: "Heinrich Hartmann's Blog"
description: "A blog about mathematics, statistics and tinkering."
url: "http://heinrichhartmann.com"

# don't show .html at the end
# permalink: pretty

# markdown: rdiscount
markdown: kramdown
# highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "Heinrich Hartmann"
      layout: "post"

plugins:
  # Figure plugin from https://github.com/lmullen/jekyll_figure
  # - jekyll_figure
  - jekyll-redirect-from

figures:
  dir: /assets
  enumerate: true

exclude: [ "_notebooks", "_templates", "Makefile" ]

include: [ ".well-known" ]
