name: "Heinrich Hartmann's Blog"
description: "A blog about mathematics, statistics and tinkering."
url: "http://heinrichhartmann.com"

# markdown: rdiscount
markdown: kramdown
# highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "Heinrich Hartmann"
      layout: "post"

# Figure plugin from
# https://github.com/lmullen/jekyll_figure
gems: [ jekyll_figure ]
#  - jekyll_figure
#  - jekyll-redirect-from

figures:
  dir: /assets
  enumerate: true
