site_name: "Elements"
site_dir: ../public/elements

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: gray
  font:
    text: source code pro
    code: source code pro
  features:
    - search.suggest
    - toc.integrate
    - navigation.sections

copyright: Copyright &copy; 2021 Heinrich Hartmann

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/heinrichhartman

plugins:
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
  - search:
      lang: en
      prebuild_index: true
  - include-markdown

markdown_extensions:
  - meta
  - footnotes
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - mdx_truly_sane_lists # https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661
  - md_in_html
  - attr_list # allow continuation of lists with  { start = 4 } syntax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # MathJax via Arithmatex
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascript/config.js
