site_name: "Heinrich Hartmann -- How to measure Latency? @ P99 CONF 2021"
site_dir: ../public/latency

theme:
  name: material
  palette:
    scheme: default # slate
  features:
    - toc.integrate
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/heinrichhartman

plugins:
  - search:
      lang: en
      prebuild_index: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - mdx_truly_sane_lists # https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661
